### ISSUE TITLE
Aggs and grouped endpoints contain "results":null

### ISSUE THREAD

**Issue by clickingbuttons** [polygon-io/issues#2]
**URL**
https://api.polygon.io/v2/aggs/grouped/locale/US/market/STOCKS/2019-03-13 for ANY day

AND

https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/day/2004-02-05/2020-02-03 for ANY symbol with daily aggregates

**Result**
Results array is empty:
```json
{"status":"OK","queryCount":0,"resultsCount":0,"adjusted":true,"results":null}
```

**Expected Result**
Results array should contain results. Retrying the request usually works.

**Additional context**
Similar to #1, this happens when calling endpoints at 200 times per second for 36k symbols (aggs endpoint) or for 4k trading days (grouped endpoint) which leads me to believe this is a caching problem. For the grouped endpoint it occurs between 5-20 times per 4k calls. It is more difficult to detect for the aggs endpoint because the `{"status":"OK","queryCount":0,"resultsCount":0,"adjusted":true,"results":null}` response is expected for symbols that did not trade in a range. However, if you request AAPL from the aggs endpoint (which certainly has traded except on market holidays) eventually you will get a null reponse.

I'm not sure how long this problem has been occurring, but it may be related to #1. If you would like a program that reproduces this, try running "Jack.java" at https://github.com/clickingbuttons/polyquest and look for errors on stdout like `null response from` which will report errors for the grouped endpoint. If you would like an exhaustive list of URLs this has occurred for me on, I have logs for about 50 occurrences.

**Comment by jbonzo** [comment]
Bug has been fixed. Resolution comment can be found in #1

**Comment by clickingbuttons** [comment]
This issue has started occurring again. In another run the following had null results:
```
null response from https://api.polygon.io/v2/aggs/grouped/locale/US/market/STOCKS/2004-06-17:
{"status":"OK","queryCount":0,"resultsCount":0,"adjusted":true,"results":null}
null response from https://api.polygon.io/v2/aggs/grouped/locale/US/market/STOCKS/2006-10-09:
{"status":"OK","queryCount":0,"resultsCount":0,"adjusted":true,"results":null}
null response from https://api.polygon.io/v2/aggs/grouped/locale/US/market/STOCKS/2009-02-05:
{"status":"OK","queryCount":0,"resultsCount":0,"adjusted":true,"results":null}
null response from https://api.polygon.io/v2/aggs/grouped/locale/US/market/STOCKS/2011-04-14:
{"status":"OK","queryCount":0,"resultsCount":0,"adjusted":true,"results":null}
```

Can you please reopen the issue?

**Comment by clickingbuttons** [comment]
@jbonzo @jrbell19 ^

**Comment by clickingbuttons** [comment]
Still happening today. Only 6 times in my latest run, but still there.

**Comment by jrbell19** [comment]
We are aware of the underlying issue that may take a bit longer to correct, but we have changed the response to 500 instead of returning misleading (null) results. I recommend just retying when you hit this 500 error. 

We'll get it sorted out as soon as possible. Will leave this issue open until then.

**Comment by clickingbuttons** [comment]
That's a big help for my error-checking code. Thanks @jrbell19 and whoever else helped!
